// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings generated from OpenCC 1.4.1 opencc.h.
class FlutterOpenCCBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterOpenCCBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterOpenCCBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Makes an instance of opencc
  ///
  /// @param configFileName Location of configuration file. If this is set to NULL,
  /// OPENCC_DEFAULT_CONFIG_SIMP_TO_TRAD will be loaded.
  /// @return            A description pointer of the newly allocated instance of
  /// opencc. On error the return value will be (opencc_t) -1.
  /// @ingroup opencc_c_api
  opencc_t opencc_open(ffi.Pointer<ffi.Char> configFileName) {
    return _opencc_open(configFileName);
  }

  late final _opencc_openPtr =
      _lookup<ffi.NativeFunction<opencc_t Function(ffi.Pointer<ffi.Char>)>>(
        'opencc_open',
      );
  late final _opencc_open = _opencc_openPtr
      .asFunction<opencc_t Function(ffi.Pointer<ffi.Char>)>();

  /// Makes an instance of opencc (wide char / Unicode)
  ///
  /// @param configFileName Location of configuration file. If this is set to NULL,
  /// OPENCC_DEFAULT_CONFIG_SIMP_TO_TRAD will be loaded.
  /// @return            A description pointer of the newly allocated instance of
  /// opencc. On error the return value will be (opencc_t) -1.
  /// @ingroup opencc_c_api
  opencc_t opencc_open_w(ffi.Pointer<ffi.WChar> configFileName) {
    return _opencc_open_w(configFileName);
  }

  late final _opencc_open_wPtr =
      _lookup<ffi.NativeFunction<opencc_t Function(ffi.Pointer<ffi.WChar>)>>(
        'opencc_open_w',
      );
  late final _opencc_open_w = _opencc_open_wPtr
      .asFunction<opencc_t Function(ffi.Pointer<ffi.WChar>)>();

  /// Destroys an instance of opencc
  ///
  /// @param opencc The description pointer.
  /// @return 0 on success or non-zero number on failure.
  /// @ingroup opencc_c_api
  int opencc_close(opencc_t opencc) {
    return _opencc_close(opencc);
  }

  late final _opencc_closePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(opencc_t)>>('opencc_close');
  late final _opencc_close = _opencc_closePtr
      .asFunction<int Function(opencc_t)>();

  /// Converts UTF-8 std::string
  ///
  /// @param opencc The opencc description pointer.
  /// @param input  The UTF-8 encoded std::string.
  /// @param length The maximum length in byte to convert. If length is (size_t)-1,
  /// the whole std::string (terminated by '\0') will be converted.
  /// @param output The buffer to store converted text. You MUST make sure this
  /// buffer has sufficient space.
  ///
  /// @return       The length of converted std::string or (size_t)-1 on error.
  ///
  /// @ingroup opencc_c_api
  int opencc_convert_utf8_to_buffer(
    opencc_t opencc,
    ffi.Pointer<ffi.Char> input,
    int length,
    ffi.Pointer<ffi.Char> output,
  ) {
    return _opencc_convert_utf8_to_buffer(opencc, input, length, output);
  }

  late final _opencc_convert_utf8_to_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Size Function(
            opencc_t,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('opencc_convert_utf8_to_buffer');
  late final _opencc_convert_utf8_to_buffer = _opencc_convert_utf8_to_bufferPtr
      .asFunction<
        int Function(
          opencc_t,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Converts UTF-8 std::string
  /// This function returns an allocated C-Style std::string, which stores
  /// the converted std::string.
  /// You MUST call opencc_convert_utf8_free() to release allocated memory.
  ///
  /// @param opencc The opencc description pointer.
  /// @param input  The UTF-8 encoded std::string.
  /// @param length The maximum length in byte to convert. If length is (size_t)-1,
  /// the whole std::string (terminated by '\0') will be converted.
  ///
  /// @return       The newly allocated UTF-8 std::string that stores text
  /// converted, or NULL on error.
  /// @ingroup opencc_c_api
  ffi.Pointer<ffi.Char> opencc_convert_utf8(
    opencc_t opencc,
    ffi.Pointer<ffi.Char> input,
    int length,
  ) {
    return _opencc_convert_utf8(opencc, input, length);
  }

  late final _opencc_convert_utf8Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            opencc_t,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('opencc_convert_utf8');
  late final _opencc_convert_utf8 = _opencc_convert_utf8Ptr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(opencc_t, ffi.Pointer<ffi.Char>, int)
      >();

  /// Releases allocated buffer by opencc_convert_utf8
  ///
  /// @param str    Pointer to the allocated std::string buffer by
  /// opencc_convert_utf8.
  ///
  /// @ingroup opencc_c_api
  void opencc_convert_utf8_free(ffi.Pointer<ffi.Char> str) {
    return _opencc_convert_utf8_free(str);
  }

  late final _opencc_convert_utf8_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'opencc_convert_utf8_free',
      );
  late final _opencc_convert_utf8_free = _opencc_convert_utf8_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Returns the last error message
  ///
  /// Note that this function is the only one which is NOT thread-safe.
  ///
  /// @ingroup opencc_c_api
  ffi.Pointer<ffi.Char> opencc_error() {
    return _opencc_error();
  }

  late final _opencc_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'opencc_error',
      );
  late final _opencc_error = _opencc_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

/// Type of opencc descriptor
///
/// @ingroup opencc_c_api
typedef opencc_t = ffi.Pointer<ffi.Void>;

const String OPENCC_DEFAULT_CONFIG_SIMP_TO_TRAD = 's2t.json';

const String OPENCC_DEFAULT_CONFIG_TRAD_TO_SIMP = 't2s.json';
